default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development
  username: postgres
  password: postgre1990

test:
  <<: *default
  database: budget_app_test
  username: postgres
  password: postgre1990

# production:
#   <<: *default
#   database: budget_app_production
#   username: budget_app
#   password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
